# Generated by Django 4.1.2 on 2022-10-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="satus",
        ),
        migrations.AddField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To do"),
                    ("in progress", "In progress"),
                    ("close", "Close"),
                ],
                default="todo",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="permissions",
            field=models.CharField(
                choices=[("restricted", "Restricted"), ("all", "All")],
                default="restricted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[
                    ("bug", "Bug"),
                    ("task", "Task"),
                    ("improvement", "Improvment"),
                ],
                default="bug",
                max_length=50,
            ),
        ),
    ]
