# Generated by Django 4.1.2 on 2022-11-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributor",
            old_name="project_id",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="contributor",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="assignee_user_id",
            new_name="assignee_user",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="project_id",
            new_name="project",
        ),
    ]
