# Generated by Django 4.1.2 on 2022-11-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_rename_project_id_contributor_project_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author_user_id",
            new_name="author_user",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="issue_id",
            new_name="issue",
        ),
    ]
