# Generated by Django 4.1.2 on 2023-01-26 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0005_rename_author_user_id_comment_author_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="author",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="permissions",
            field=models.CharField(
                choices=[("restricted", "Contributor"), ("all", "Author")],
                default="restricted",
                max_length=50,
            ),
        ),
    ]
